export const planetChartData = {
    type: 'bar',
    data: {
      labels: [ 'COVID19',
      'Požareport',
      'koronavirus',
      'Slovenia',
      'OstaniZdrav',
      'govoricatelesa',
      'EU',
      'Covid_19',
      'coronavirus',
      'sampovem',
      'levuhad',
      'Slovenija',
      'Covid19',
      'MSM',
      'žilneopornice',
      'Antifa',
      'DeltaLifeCoaching',
      'tako',
      'tvit',
      'dober',
      'porušitiRTVHanzi',
      'video',
      'covid19',
      'bucibuc',
      'ronikordis',
      'TDF2020',
      'dan',
      'vsak',
      'komunikacija',
      'NPU',
      'BlackLivesMatter',
      'tarča',
      'sLOVEnija',
      'faktor',
      'avijončki',
      'corrupt',
      'FakeNews',
      'prvorazredni',
      'EUCO',
      'PKP3',
      'MFF',
      'življenje',
      'COVIDー19',
      'BLM',
      'samopovem',
      'PKP1',
      'Faktor',
      'Nadanašnjidan',
      'ostanidoma',
      'had',
      'KPK',
      'BREAKING',
      'bingo',
      'Belarus',
      'javniprevoz',
      'antifa',
      'Auschwitz',
      'SFRJ',
      'respect',
      'IranNLBgate',
      'SDS',
      'Radonjić',
      'FoxNews',
      'seja',
      'samprašam',
      'Trump',
      'AntifaTerrorists',
      'PrayRosary',
      'Pray',
      'dlc',
      'PKP2',
      'butale',
      'DZ',
      'SAB',
      'msm',
      'Trump2020',
      'SARSCoV2',
      'PM',
      'naskaluc',
      'MAGA',
      'samprasam',
      'Ljubljana',
      'tarca',
      'PKP5',
      'fakenews',
      'Zmoremo',
      'COVID',
      'potniki',
      'nasvet',
      'sarkazem',
      'Novič',
      'sarcasm',
      'Slovenian',
      'EvropejciProtiCOVID19',
      'US',
      'USA',
      'sramota',
      'Election2020',
      'DLC',
      'Tarča' ],    
      datasets: [
        { // another line graph
          label: 'Top hashtags for 500 users from October 2019',
          data: [ 5031,
            3342,
            2345,
            1523,
            1389,
            1324,
            1234,
            1170,
            1024,
            993,
            984,
            979,
            934,
            764,
            733,
            710,
            699,
            659,
            645,
            641,
            629,
            619,
            617,
            605,
            594,
            559,
            530,
            527,
            519,
            501,
            497,
            477,
            458,
            438,
            434,
            420,
            418,
            414,
            412,
            390,
            345,
            344,
            341,
            337,
            328,
            323,
            322,
            310,
            307,
            302,
            298,
            293,
            291,
            290,
            285,
            277,
            271,
            268,
            268,
            266,
            262,
            248,
            244,
            239,
            237,
            235,
            235,
            233,
            231,
            230,
            227,
            227,
            227,
            225,
            223,
            222,
            222,
            222,
            217,
            216,
            214,
            214,
            214,
            211,
            210,
            209,
            203,
            202,
            197,
            196,
            192,
            191,
            190,
            190,
            188,
            185,
            185,
            185,
            185,
            183 ]
          ,
          backgroundColor: 'rgba(71, 183,132,.5)', // Green
          borderColor: '#47b784',
          borderWidth: 3
        }
      ]
    },
    options: {
      responsive: true,
      lineTension: 1,
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true,
            padding: 25,
          }
        }]
      }
    }
  }
  
  export default planetChartData;